"""Lexicons and helper data for rule-based semantics."""

NEGATIONS = {
    "not",
    "no",
    "never",
    "none",
    "nobody",
    "nothing",
    "neither",
    "nowhere",
    "hardly",
    "scarcely",
    "barely",
}

INTENSIFIERS = {
    "very",
    "extremely",
    "really",
    "so",
    "too",
    "quite",
    "highly",
    "deeply",
    "utterly",
}

DIMINISHERS = {
    "slightly",
    "somewhat",
    "a_bit",
    "barely",
    "hardly",
    "sort_of",
    "kind_of",
}

MODALITY = {
    "must": "obligation",
    "should": "recommendation",
    "ought": "recommendation",
    "may": "permission",
    "might": "possibility",
    "could": "possibility",
    "can": "ability",
    "will": "future",
    "would": "conditional",
}

TEMPORAL_CUES = {
    "yesterday": "past",
    "today": "present",
    "tomorrow": "future",
    "now": "present",
    "currently": "present",
    "soon": "future",
    "later": "future",
    "previously": "past",
    "recently": "past",
}

PRONOUNS = {
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "her",
    "their",
    "our",
}

DETERMINERS = {
    "a",
    "an",
    "the",
    "this",
    "that",
    "these",
    "those",
    "each",
    "every",
    "some",
    "any",
    "no",
    "all",
    "most",
}

QUANTIFIERS = {
    "all": "universal",
    "every": "universal",
    "each": "distributive",
    "many": "plural",
    "few": "small_amount",
    "some": "existential",
    "any": "open",
    "several": "plural",
    "most": "majority",
    "none": "zero",
}

QUESTION_WORDS = {"who", "what", "when", "where", "why", "how", "which"}

SENTIMENT_POSITIVE = {
    "happy",
    "joy",
    "love",
    "great",
    "excellent",
    "good",
    "wonderful",
    "amazing",
    "success",
    "positive",
}

SENTIMENT_NEGATIVE = {
    "sad",
    "angry",
    "hate",
    "bad",
    "terrible",
    "awful",
    "horrible",
    "failure",
    "negative",
    "poor",
}

COMMON_VERBS = {
    "be",
    "am",
    "is",
    "are",
    "was",
    "were",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "say",
    "make",
    "go",
    "get",
    "see",
    "know",
    "think",
    "take",
    "come",
    "give",
    "find",
    "tell",
    "work",
    "call",
    "try",
    "ask",
    "need",
    "feel",
    "become",
    "leave",
    "put",
    "mean",
    "keep",
    "let",
    "begin",
    "help",
    "talk",
    "turn",
    "like",
    "start",
    "show",
    "hear",
    "play",
    "run",
    "move",
    "live",
    "believe",
    "bring",
    "happen",
    "write",
    "provide",
    "sit",
    "stand",
    "lose",
    "pay",
    "meet",
    "include",
    "continue",
    "set",
    "learn",
    "change",
    "lead",
    "understand",
    "watch",
    "follow",
    "stop",
    "create",
    "speak",
    "read",
    "allow",
    "add",
    "spend",
    "grow",
    "open",
    "walk",
    "win",
    "teach",
}

ADJECTIVE_SUFFIXES = ("ous", "ful", "able", "ible", "al", "ive", "less", "ic", "ish")
ADVERB_SUFFIXES = ("ly",)
VERB_SUFFIXES = ("ed", "ing", "en", "ify", "ise", "ize")
